# Book settings
title: 9447H - Engineering Notebook
author: 9447H - Brody Muzzy, Derek Mullins, Dylan Quinn, Ian Smith, Jack Kinsella
logo: v1logo.png
url: https://JKinsella04.github.io/OperationPheasant/blobl/master/engineBook/

latex:
  latex_documents:
    targetname: book.tex
