# Book settings
title: 9447H - Engineering Notebook
author: 9447H
logo: images/beginning/v1logo.png
site_url: https://JKinsella04.github.io/OperationPheasant/

latex:
  latex_documents:
    targetname: book.tex
